version: '3.3'
services:
  quassel-core:
    image: linuxserver/quassel-core
    container_name: quassel-core
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=NewZealand/Auckland
#      - RUN_OPTS=--config-from-environment #optional
    volumes:
      - /mnt/docker/quassel-core:/config
    ports:
      - 4242:4242
      - 113:10113 #optional
    restart: unless-stopped
  quassel-web:
    image: linuxserver/quassel-web
    container_name: quassel-web
    environment:
      - PUID=1000
      - PGID=1000
      - QUASSEL_CORE=10.1.1.15
      - QUASSEL_PORT=4242
      - URL_BASE=/quassel #optional
    volumes:
      - /mnt/docker/quassel-web:/config
    ports:
      - 64080:64080
    restart: unless-stopped
